const UNIVERSITY_ROUTES = [
  // ── Dhaka University ──────────────────────────────────────
  {
    id: "route_01",
    label: "Mirpur 10 → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Mirpur 10 Roundabout",    area: "Mirpur",        lat: 23.8103, lng: 90.3654 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 11,
  },
  {
    id: "route_02",
    label: "Uttara → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Uttara Sector 7",          area: "Uttara",        lat: 23.8759, lng: 90.3795 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 18,
  },
  {
    id: "route_03",
    label: "Mohammadpur → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Mohammadpur Bus Stand",    area: "Mohammadpur",   lat: 23.7616, lng: 90.3572 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 6,
  },
  {
    id: "route_04",
    label: "Rampura → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Rampura Bridge",           area: "Rampura",       lat: 23.7574, lng: 90.4292 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 8,
  },
  {
    id: "route_05",
    label: "Motijheel → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Motijheel Shapla Circle",  area: "Motijheel",     lat: 23.7279, lng: 90.4176 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 5,
  },
  {
    id: "route_06",
    label: "Farmgate → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Farmgate Bus Stop",        area: "Farmgate",      lat: 23.7582, lng: 90.3896 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 4,
  },
  {
    id: "route_07",
    label: "Jigatola → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Jigatola Bus Stand",       area: "Jigatola",      lat: 23.7366, lng: 90.3756 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 3,
  },
  {
    id: "route_08",
    label: "Khilgaon → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Khilgaon Chowrasta",       area: "Khilgaon",      lat: 23.7412, lng: 90.4268 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 7,
  },
  {
    id: "route_09",
    label: "Demra → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Demra Staff Quarter",      area: "Demra",         lat: 23.7204, lng: 90.4706 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 12,
  },
  {
    id: "route_10",
    label: "Narayanganj → Dhaka University",
    university: "Dhaka University",
    origin:      { name: "Narayanganj Bus Terminal", area: "Narayanganj",   lat: 23.6238, lng: 90.4998 },
    destination: { name: "Dhaka University",         area: "Nilkhet",       lat: 23.7272, lng: 90.3960 },
    estimatedKm: 22,
  },

  // ── BUET ──────────────────────────────────────────────────
  {
    id: "route_11",
    label: "Uttara → BUET",
    university: "BUET",
    origin:      { name: "Uttara Sector 7",          area: "Uttara",        lat: 23.8759, lng: 90.3795 },
    destination: { name: "BUET Main Gate",           area: "Palashi",       lat: 23.7261, lng: 90.3927 },
    estimatedKm: 17,
  },
  {
    id: "route_12",
    label: "Mirpur 1 → BUET",
    university: "BUET",
    origin:      { name: "Mirpur 1",                 area: "Mirpur",        lat: 23.7926, lng: 90.3584 },
    destination: { name: "BUET Main Gate",           area: "Palashi",       lat: 23.7261, lng: 90.3927 },
    estimatedKm: 9,
  },
  {
    id: "route_13",
    label: "Pallabi → BUET",
    university: "BUET",
    origin:      { name: "Pallabi Bus Stand",        area: "Pallabi",       lat: 23.8274, lng: 90.3614 },
    destination: { name: "BUET Main Gate",           area: "Palashi",       lat: 23.7261, lng: 90.3927 },
    estimatedKm: 13,
  },
  {
    id: "route_14",
    label: "Azimpur → BUET",
    university: "BUET",
    origin:      { name: "Azimpur Bus Stand",        area: "Azimpur",       lat: 23.7225, lng: 90.3853 },
    destination: { name: "BUET Main Gate",           area: "Palashi",       lat: 23.7261, lng: 90.3927 },
    estimatedKm: 2,
  },
  {
    id: "route_15",
    label: "Elephant Road → BUET",
    university: "BUET",
    origin:      { name: "Elephant Road",            area: "Elephant Road", lat: 23.7380, lng: 90.3888 },
    destination: { name: "BUET Main Gate",           area: "Palashi",       lat: 23.7261, lng: 90.3927 },
    estimatedKm: 2,
  },
  {
    id: "route_16",
    label: "Dhanmondi → BUET",
    university: "BUET",
    origin:      { name: "Dhanmondi 27",             area: "Dhanmondi",     lat: 23.7465, lng: 90.3707 },
    destination: { name: "BUET Main Gate",           area: "Palashi",       lat: 23.7261, lng: 90.3927 },
    estimatedKm: 5,
  },

  // ── NSU ───────────────────────────────────────────────────
  {
    id: "route_17",
    label: "Bashundhara → NSU",
    university: "NSU",
    origin:      { name: "Bashundhara R/A Gate",     area: "Bashundhara",   lat: 23.8141, lng: 90.4275 },
    destination: { name: "North South University",   area: "Bashundhara",   lat: 23.8148, lng: 90.4244 },
    estimatedKm: 3,
  },
  {
    id: "route_18",
    label: "Gulshan 2 → NSU",
    university: "NSU",
    origin:      { name: "Gulshan 2 Circle",         area: "Gulshan",       lat: 23.7936, lng: 90.4149 },
    destination: { name: "North South University",   area: "Bashundhara",   lat: 23.8148, lng: 90.4244 },
    estimatedKm: 5,
  },
  {
    id: "route_19",
    label: "Banani → NSU",
    university: "NSU",
    origin:      { name: "Banani Chairman Bari",     area: "Banani",        lat: 23.7937, lng: 90.4066 },
    destination: { name: "North South University",   area: "Bashundhara",   lat: 23.8148, lng: 90.4244 },
    estimatedKm: 4,
  },
  {
    id: "route_20",
    label: "Badda → NSU",
    university: "NSU",
    origin:      { name: "Badda Link Road",          area: "Badda",         lat: 23.7826, lng: 90.4278 },
    destination: { name: "North South University",   area: "Bashundhara",   lat: 23.8148, lng: 90.4244 },
    estimatedKm: 6,
  },
  {
    id: "route_21",
    label: "Uttara → NSU",
    university: "NSU",
    origin:      { name: "Uttara Sector 3",          area: "Uttara",        lat: 23.8716, lng: 90.3854 },
    destination: { name: "North South University",   area: "Bashundhara",   lat: 23.8148, lng: 90.4244 },
    estimatedKm: 10,
  },
  {
    id: "route_22",
    label: "Gazipur → NSU",
    university: "NSU",
    origin:      { name: "Gazipur Chowrasta",        area: "Gazipur",       lat: 23.9999, lng: 90.4203 },
    destination: { name: "North South University",   area: "Bashundhara",   lat: 23.8148, lng: 90.4244 },
    estimatedKm: 24,
  },

  // ── BRAC University ───────────────────────────────────────
  {
    id: "route_23",
    label: "Dhanmondi → BRAC University",
    university: "BRAC University",
    origin:      { name: "Dhanmondi 27",             area: "Dhanmondi",     lat: 23.7465, lng: 90.3707 },
    destination: { name: "BRAC University",          area: "Mohakhali",     lat: 23.7808, lng: 90.4042 },
    estimatedKm: 7,
  },
  {
    id: "route_24",
    label: "Uttara → BRAC University",
    university: "BRAC University",
    origin:      { name: "Uttara Sector 3",          area: "Uttara",        lat: 23.8716, lng: 90.3854 },
    destination: { name: "BRAC University",          area: "Mohakhali",     lat: 23.7808, lng: 90.4042 },
    estimatedKm: 12,
  },
  {
    id: "route_25",
    label: "Tejgaon → BRAC University",
    university: "BRAC University",
    origin:      { name: "Tejgaon Link Road",        area: "Tejgaon",       lat: 23.7633, lng: 90.3956 },
    destination: { name: "BRAC University",          area: "Mohakhali",     lat: 23.7808, lng: 90.4042 },
    estimatedKm: 3,
  },
  {
    id: "route_26",
    label: "Mirpur 10 → BRAC University",
    university: "BRAC University",
    origin:      { name: "Mirpur 10 Roundabout",     area: "Mirpur",        lat: 23.8103, lng: 90.3654 },
    destination: { name: "BRAC University",          area: "Mohakhali",     lat: 23.7808, lng: 90.4042 },
    estimatedKm: 9,
  },

  // ── IUB ───────────────────────────────────────────────────
  {
    id: "route_27",
    label: "Mirpur 10 → IUB",
    university: "IUB",
    origin:      { name: "Mirpur 10 Roundabout",     area: "Mirpur",        lat: 23.8103, lng: 90.3654 },
    destination: { name: "Independent University",   area: "Bashundhara",   lat: 23.8130, lng: 90.4280 },
    estimatedKm: 8,
  },
  {
    id: "route_28",
    label: "Gulshan 1 → IUB",
    university: "IUB",
    origin:      { name: "Gulshan 1 Circle",         area: "Gulshan",       lat: 23.7808, lng: 90.4147 },
    destination: { name: "Independent University",   area: "Bashundhara",   lat: 23.8130, lng: 90.4280 },
    estimatedKm: 5,
  },

  // ── East West University ──────────────────────────────────
  {
    id: "route_29",
    label: "Mirpur 12 → East West University",
    university: "East West University",
    origin:      { name: "Mirpur 12",                area: "Mirpur",        lat: 23.8245, lng: 90.3682 },
    destination: { name: "East West University",     area: "Aftabnagar",    lat: 23.7538, lng: 90.4267 },
    estimatedKm: 14,
  },
  {
    id: "route_30",
    label: "Rampura → East West University",
    university: "East West University",
    origin:      { name: "Rampura Bridge",           area: "Rampura",       lat: 23.7574, lng: 90.4292 },
    destination: { name: "East West University",     area: "Aftabnagar",    lat: 23.7538, lng: 90.4267 },
    estimatedKm: 3,
  },

  // ── MIST ──────────────────────────────────────────────────
  {
    id: "route_31",
    label: "Manikdi → MIST",
    university: "MIST",
    origin:      { name: "Manikdi Bus Stop",         area: "Manikdi",       lat: 23.8368, lng: 90.3994 },
    destination: { name: "MIST, Mirpur",             area: "Mirpur",        lat: 23.8219, lng: 90.3652 },
    estimatedKm: 4,
  },
  {
    id: "route_32",
    label: "Uttara → MIST",
    university: "MIST",
    origin:      { name: "Uttara Sector 10",         area: "Uttara",        lat: 23.8716, lng: 90.3854 },
    destination: { name: "MIST, Mirpur",             area: "Mirpur",        lat: 23.8219, lng: 90.3652 },
    estimatedKm: 7,
  },

  // ── UIU ───────────────────────────────────────────────────
  {
    id: "route_33",
    label: "Badda → UIU",
    university: "UIU",
    origin:      { name: "Badda Link Road",          area: "Badda",         lat: 23.7826, lng: 90.4278 },
    destination: { name: "United International Uni", area: "Satarkul",      lat: 23.8200, lng: 90.4394 },
    estimatedKm: 5,
  },
  {
    id: "route_34",
    label: "Gulshan 2 → UIU",
    university: "UIU",
    origin:      { name: "Gulshan 2 Circle",         area: "Gulshan",       lat: 23.7936, lng: 90.4149 },
    destination: { name: "United International Uni", area: "Satarkul",      lat: 23.8200, lng: 90.4394 },
    estimatedKm: 7,
  },

  // ── AIUB ──────────────────────────────────────────────────
  {
    id: "route_35",
    label: "Uttara → AIUB",
    university: "AIUB",
    origin:      { name: "Uttara Sector 4",          area: "Uttara",        lat: 23.8716, lng: 90.3854 },
    destination: { name: "AIUB, Kuratoli",           area: "Kuratoli",      lat: 23.8747, lng: 90.4272 },
    estimatedKm: 6,
  },
  {
    id: "route_36",
    label: "Bashundhara → AIUB",
    university: "AIUB",
    origin:      { name: "Bashundhara R/A Gate",     area: "Bashundhara",   lat: 23.8141, lng: 90.4275 },
    destination: { name: "AIUB, Kuratoli",           area: "Kuratoli",      lat: 23.8747, lng: 90.4272 },
    estimatedKm: 8,
  },

  // ── Jahangirnagar University ──────────────────────────────
  {
    id: "route_37",
    label: "Mirpur → Jahangirnagar University",
    university: "Jahangirnagar University",
    origin:      { name: "Mirpur 10 Roundabout",     area: "Mirpur",        lat: 23.8103, lng: 90.3654 },
    destination: { name: "Jahangirnagar University", area: "Savar",         lat: 23.8815, lng: 90.2677 },
    estimatedKm: 28,
  },
  {
    id: "route_38",
    label: "Gabtoli → Jahangirnagar University",
    university: "Jahangirnagar University",
    origin:      { name: "Gabtoli Bus Terminal",     area: "Gabtoli",       lat: 23.7756, lng: 90.3389 },
    destination: { name: "Jahangirnagar University", area: "Savar",         lat: 23.8815, lng: 90.2677 },
    estimatedKm: 20,
  },

  // ── Stamford University ───────────────────────────────────
  {
    id: "route_39",
    label: "Dhanmondi → Stamford University",
    university: "Stamford University",
    origin:      { name: "Dhanmondi 15",             area: "Dhanmondi",     lat: 23.7465, lng: 90.3707 },
    destination: { name: "Stamford University",      area: "Siddeswari",    lat: 23.7396, lng: 90.4035 },
    estimatedKm: 5,
  },
  {
    id: "route_40",
    label: "Motijheel → Stamford University",
    university: "Stamford University",
    origin:      { name: "Motijheel Shapla Circle",  area: "Motijheel",     lat: 23.7279, lng: 90.4176 },
    destination: { name: "Stamford University",      area: "Siddeswari",    lat: 23.7396, lng: 90.4035 },
    estimatedKm: 3,
  },
];

export default UNIVERSITY_ROUTES;